name: Deploy FE Service Stack
env:
  CI: false
on: 
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-southeast-1'
      network-stack:
        description: "Network/VPC Stack"
        required: true
        default: bs-network-stack
      stack-name:
        description: "Name of deploying stack"
        required: true
        default: bs-fe-service

jobs:
  check-release-images:
    runs-on: ubuntu-latest
    outputs:
      FE_IMAGE: ${{ steps.fe_release_version.outputs.value }}
    steps:
    -
      name: Get latest FE release image
      uses: sergeysova/jq-action@v2
      id: fe_release_version
      with: 
        cmd: wget -q https://registry.hub.docker.com/v1/repositories/minimicrowave/bs-ui/tags -O - | jq -r 'map(select(.name | contains("RELEASE"))) | last | .name'

    - 
      name: Show FE release version
      run: > 
        echo "FE version: ${{ steps.fe_release_version.outputs.value }}"
    - 
      name: Release image check
      if: steps.fe_release_version.outputs.value  == 'null'
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('FE release version missing!')
  
  deploy-service-stack:
    needs: check-release-images
    runs-on: ubuntu-latest
    steps:
    -
      run: echo Deploying FE - docker.io/minimicrowave/bs-ui:${{needs.check-release-images.outputs.FE_IMAGE}}
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}
    - 
      name: Deploy Service Stack
      id: service-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
      with:
        name: ${{ github.event.inputs.stack-name }}
        template: service-fe.yml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          NetworkStackName=${{ github.event.inputs.network-stack }},
          ServiceName=${{ github.event.inputs.stack-name }},
          ImageUrl=docker.io/minimicrowave/bs-ui:${{ needs.check-release-images.outputs.FE_IMAGE }},
          ContainerPort=80,
          HealthCheckPath=/
