name: Deploy CloudFormation Service 
env:
  CI: false
on: [ push ]

jobs:
  deploy-service-stack:
    runs-on: ubuntu-latest
    steps:
    -
      name: Get latest FE release image
      uses: sergeysova/jq-action@v2
      id: fe_release_version
      with: 
        cmd: wget -q https://registry.hub.docker.com/v1/repositories/minimicrowave/bs-ui/tags -O - | jq 'map(select(.name | contains("RELEASE"))) | last | .[0].name'

    - 
      name: Get latest BE release image
      uses: sergeysova/jq-action@v2
      id: be_release_version
      with: 
        cmd: wget -q https://registry.hub.docker.com/v1/repositories/minimicrowave/bs-api/tags -O - | jq 'map(select(.name | contains("RELEASE"))) | last | .name'
    
    - 
      name: Show BE and FE release versions
      run: 'echo "version ${{ steps.fe_release_version.outputs.value }}" "version ${{ steps.be_release_version.outputs.value }}"'
    - 
      name: Release image check
      if: ${{ steps.fe_release_version.outputs.value }} = "null" || ${{ steps.be_release_version.outputs.value }} = "null"
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('FE or BE release versions missing!')