name: Deploy Service Stack
env:
  CI: false
on: 
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-southeast-1'

jobs:
  check-release-images:
    runs-on: ubuntu-latest
    outputs:
      FE_IMAGE: ${{ steps.fe_release_version.outputs.value }}
      BE_IMAGE: ${{ steps.be_release_version.outputs.value }}
    steps:
    -
      name: Get latest FE release image
      uses: sergeysova/jq-action@v2
      id: fe_release_version
      with: 
        cmd: wget -q https://registry.hub.docker.com/v1/repositories/minimicrowave/bs-ui/tags -O - | jq 'map(select(.name | contains("RELEASE"))) | last | .name'

    - 
      name: Get latest BE release image
      uses: sergeysova/jq-action@v2
      id: be_release_version
      with: 
        cmd: wget -q https://registry.hub.docker.com/v1/repositories/minimicrowave/bs-api/tags -O - | jq 'map(select(.name | contains("RELEASE"))) | last | .name'
    
    - 
      name: Show BE and FE release versions
      run: > 
        echo "FE version: ${{ steps.fe_release_version.outputs.value }}, BE version: ${{ steps.be_release_version.outputs.value }}"
    - 
      name: Release image check
      if: steps.fe_release_version.outputs.value  == 'null' || steps.be_release_version.outputs.value == 'null'
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('FE or BE release versions missing!')
  
  deploy-service-stack:
    needs: check-release-images
    runs-on: ubuntu-latest
    steps:
    -
      run: echo Deploying FE - ${{needs.check-release-images.outputs.FE_IMAGE}}, BE - ${{needs.check-release-images.outputs.BE_IMAGE}}
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region}}
    - 
      name: Deploy Service Stack
      id: service-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
      with:
        name: bs-service-stack
        template: service.yml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          NetworkStackName=bs-network-stack,
          DatabaseStackName=bs-rds-stack,
          ServiceName=bs-service,
          FEImageUrl=docker.io/minimicrowave/bs-ui:${{needs.check-release-images.outputs.FE_IMAGE}},
          BEImageUrl=docker.io/minimicrowave/bs-api:${{needs.check-release-images.outputs.BE_IMAGE}}