name: Test PAT

on: 
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-southeast-1'


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    -
      run: echo pat testtttt